git:
  autoFetch: true
  nerdFontsVersion: "3"
  autoRefresh: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium
os:
  editCommand: "nvim"
  editCommandTemplate: "{{editor}} +{{line}} {{filename}}"
  openCommand: "open {{filename}}"
  openLinkCommand: "open {{link}}"
