-- -- Define your color variables
-- local primary = 'rgb(4caf50)'
-- local outline = 'rgb(8c9388)'
-- local error = 'rgb(f2b8b5)'
--
-- -- General borders
-- hl.config = { general = {
--   ['col.active_border'] = primary,
--   ['col.inactive_border'] = outline,
-- } }
--
-- -- Group and Groupbar settings
-- hl.group {
--   ['col.border_active'] = primary,
--   ['col.border_inactive'] = outline,
--   ['col.border_locked_active'] = error,
--   ['col.border_locked_inactive'] = outline,
--
--   groupbar = {
--     ['col.active'] = primary,
--     ['col.inactive'] = outline,
--     ['col.locked_active'] = error,
--     ['col.locked_inactive'] = outline,
--   },
-- }
