[manager]
prepend_keymap = [
  { on = [
    "!",
  ], run = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
  { on = [
    "m",
  ], run = "plugin bookmarks --args=save", desc = "Save current position as a bookmark" },
  { on = [
    "'",
  ], run = "plugin bookmarks --args=jump", desc = "Jump to a bookmark" },
  { on = [
    "b",
    "d",
  ], run = "plugin bookmarks --args=delete", desc = "Delete a bookmark" },
  { on = [
    "b",
    "D",
  ], run = "plugin bookmarks --args=delete_all", desc = "Delete all bookmarks" },
]
