local icons = {
	diagnostics = {
		error = "",
		warn = "",
		hint = "",
		info = "",
		Warn = "",
		Info = "",
		Error = " ",
		Hint = " ",
		Information = " ",
		Question = " ",
		Warning = " ",
	},
	git = {
		added = "",
		modified = "",
		removed = "",
		renamed = "➜",
		untracked = "",
		ignored = "",
		unstaged = "U",
		staged = "",
		conflict = "",
		deleted = "",
		Add = " ",
		Diff = " ",
		Ignore = " ",
		Mod = " ",
		Remove = " ",
		Rename = " ",
		Repo = " ",
	},
	gitsigns = {
		add = "┃",
		change = "┋",
		delete = "",
		topdelhfe = "",
		changedelete = "┃",
		untracked = "┃",
	},
	kinds = {
		Array = "",
		Boolean = "",
		Class = "",
		Color = "",
		Constant = "",
		Constructor = "",
		Copilot = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "",
		File = "",
		Folder = "",
		Function = "",
		Interface = "",
		Key = "",
		Keyword = "",
		Method = "",
		Module = "",
		Namespace = "",
		Null = "",
		Number = "",
		Object = "",
		Operator = "",
		Package = "",
		Property = "",
		Reference = "",
		Snippet = "",
		String = "",
		Struct = "",
		Text = "",
		TypeParameter = "",
		Unit = "",
		Value = "",
		Variable = "",
		Macro = "", -- Macro
	},
	borders = {
		--- @class BorderIcons
		thin = {
			top = "▔",
			right = "▕",
			bottom = "▁",
			left = "▏",
			top_left = "🭽",
			top_right = "🭾",
			bottom_right = "🭿",
			bottom_left = "🭼",
		},
		---@type BorderIcons
		empty = {
			top = " ",
			right = " ",
			bottom = " ",
			left = " ",
			top_left = " ",
			top_right = " ",
			bottom_right = " ",
			bottom_left = " ",
		},
		---@type BorderIcons
		thick = {
			top = "▄",
			right = "█",
			bottom = "▀",
			left = "█",
			top_left = "▄",
			top_right = "▄",
			bottom_right = "▀",
			bottom_left = "▀",
		},
	},
	arrows = {
		ArrowRight = "❯",
		ArrowLeft = "❮",
		-- ChevronRight = "",
		ChevronRight = ">",
		CurvedArrowRight = " ",
		DoubleArrowRight = "»",
		SmallArrowRight = "➜",
		Diamond = "<>",
	},
	ui = {
		BigCircle = " ",
		BigUnfilledCircle = " ",
		BookMark = " ",
		Bug = " ",
		Calendar = " ",
		Check = " ",
		Circle = " ",
		Close = " ",
		Code = " ",
		Comment = " ",
		Dashboard = " ",
		Fire = " ",
		Gear = " ",
		History = " ",
		Lightbulb = " ",
		List = " ",
		Lock = " ",
		NewFile = " ",
		Note = " ",
		Package = " ",
		Pencil = " ",
		Plus = "+",
		Project = " ",
		RunningMan = "🏃",
		Search = " ",
		SignIn = " ",
		Table = " ",
		Telescope = " ",
		Yoga = "🧘",
		Xmark = "✗",
	},
	misc = {
		abc = "  ",
		array = "  ",
		arrowReturn = "  ",
		bigCircle = "  ",
		bigUnfilledCircle = "  ",
		bomb = "  ",
		bookMark = "  ",
		boolean = " 蘒",
		box = "  ",
		buffer = " ﬘ ",
		bug = "  ",
		calculator = "  ",
		calendar = "  ",
		caretRight = "",
		check = "  ",
		checkSquare = "  ",
		copilot = "",
		codeium = "",
		exit = "  ",
		chevronRight = "",
		circle = "  ",
		class = "  ",
		close = "  ",
		code = "  ",
		cog = "  ",
		color = "  ",
		comment = "  ",
		constant = "  ",
		constructor = "  ",
		container = "  ",
		console = " 󰞷 ",
		consoleDebug = "  ",
		cubeTree = "  ",
		curlies = "  ",
		dashboard = "  ",
		database = "  ",
		emptyBox = "  ",
		enum = "  ",
		enumMember = "  ",
		error = "  ",
		errorOutline = "  ",
		errorSlash = " ﰸ ",
		event = "  ",
		f = "  ",
		field = "  ",
		file = "  ",
		fileBg = "  ",
		fileCopy = "  ",
		fileCutCorner = "  ",
		fileNoBg = "  ",
		fileNoLines = "  ",
		fileNoLinesBg = "  ",
		fileRecent = "  ",
		fire = "  ",
		folder = "  ",
		folderNoBg = "  ",
		folderOpen = "  ",
		folderOpen2 = " ﱮ ",
		folderOpenNoBg = "  ",
		forbidden = "  ",
		func = "  ",
		gear = "  ",
		gears = "  ",
		git = "  ",
		gitAdd = "  ",
		gitChange = " 柳",
		gitRemove = "  ",
		happyFace = " ﲃ ",
		hexCutOut = "  ",
		history = "  ",
		hook = " ﯠ ",
		info = "  ",
		infoOutline = "  ",
		interface = "  ",
		key = "  ",
		keyword = "  ",
		light = "  ",
		lightbulb = "  ",
		lightbulbOutline = "  ",
		list = "  ",
		lock = "  ",
		m = " m ",
		method = "  ",
		module = "  ",
		newFile = "  ",
		note = "  ",
		number = "  ",
		numbers = "  ",
		object = "  ",
		operator = "  ",
		package = "  ",
		packageUp = "  ",
		packageDown = "  ",
		paint = "  ",
		paragraph = "  ",
		pencil = "  ",
		pie = "  ",
		pin = " 󰐃 ",
		project = "  ",
		property = "  ",
		questionCircle = "  ",
		rectangleIntersect = " 練",
		reference = "  ",
		ribbon = "  ",
		ribbonNoBg = "  ",
		robot = " ﮧ ",
		ruler = " 塞",
		scissors = "  ",
		scope = "  ",
		search = "  ",
		settings = "  ",
		signIn = "  ",
		snippet = "  ",
		sort = "  ",
		stack = "  ",
		spell = " 暈",
		squirrel = "  ",
		string = "  ",
		struct = "  ",
		t = "  ",
		table = "  ",
		tag = "  ",
		telescope = "  ",
		terminal = "  ",
		text = "  ",
		threeDots = "  ",
		threeDotsBoxed = "  ",
		timer = "  ",
		toggleSelected = " 蘒",
		trash = "  ",
		tree = "  ",
		treeDiagram = "  ",
		typeParameter = "  ",
		unit = "  ",
		up_hexagon = "  ",
		value = "  ",
		variable = "  ",
		vim = "  ",
		warningCircle = "  ",
		warningTriangle = "  ",
		warningTriangleNoBg = "  ",
		watch = "  ",
		word = "  ",
		wrench = "  ",
	},
	codicons = {
		Text = "",
		Method = "",
		Function = "",
		Constructor = "",
		Field = "",
		Variable = "",
		Class = "",
		Interface = "",
		Module = "",
		Property = "",
		Unit = "",
		Value = "",
		Enum = "",
		Keyword = "",
		Snippet = "",
		Color = "",
		File = "",
		Reference = "",
		Folder = "",
		EnumMember = "",
		Constant = "",
		Struct = "",
		Event = "",
		Operator = "",
		TypeParameter = "",
	},
}

return {
	"utilyre/barbecue.nvim",
	name = "barbecue",
	dependencies = {
		"SmiteshP/nvim-navic",
		"nvim-tree/nvim-web-devicons",
	},
	---@type barbecue.Config
	opts = {
		theme = "catppuccin",
	},
	config = function()
		vim.opt.updatetime = 200

		require("barbecue").setup({
			create_autocmd = false, -- prevent barbecue from updating itself automatically
			attach_navic = true,
			include_buftypes = { "" },
			exclude_filetypes = { "alpha", "gitcommit", "netrw", "toggleterm", "Trouble" },
			modifiers = {
				dirname = ":~:.",
				basename = "",
			},
			show_dirname = true,
			show_basename = false,
			show_modified = false,
			modified = function(bufnr)
				return vim.bo[bufnr].modified
			end,
			show_navic = true,
			lead_custom_section = function()
				return " "
			end,
			custom_section = function()
				return ""
			end,
			theme = {
				normal = { fg = "#c0caf5" },
				ellipsis = { fg = "#737aa2" },
				separator = { fg = "#737aa2" },
				modified = { fg = "#737aa2" },
				dirname = { fg = "#488dff" },
				basename = { bold = true },
				context = {},
				context_file = { fg = "#ac8fe4" },
				context_module = { fg = "#ac8fe4" },
				context_namespace = { fg = "#ac8fe4" },
				context_package = { fg = "#ac8fe4" },
				context_class = { fg = "#ac8fe4" },
				context_method = { fg = "#ac8fe4" },
				context_property = { fg = "#ac8fe4" },
				context_field = { fg = "#ac8fe4" },
				context_constructor = { fg = "#ac8fe4" },
				context_enum = { fg = "#ac8fe4" },
				context_interface = { fg = "#ac8fe4" },
				context_function = { fg = "#ac8fe4" },
				context_variable = { fg = "#ac8fe4" },
				context_constant = { fg = "#ac8fe4" },
				context_string = { fg = "#ac8fe4" },
				context_number = { fg = "#ac8fe4" },
				context_boolean = { fg = "#ac8fe4" },
				context_array = { fg = "#ac8fe4" },
				context_object = { fg = "#ac8fe4" },
				context_key = { fg = "#ac8fe4" },
				context_null = { fg = "#ac8fe4" },
				context_enum_member = { fg = "#ac8fe4" },
				context_struct = { fg = "#ac8fe4" },
				context_event = { fg = "#ac8fe4" },
				context_operator = { fg = "#ac8fe4" },
				context_type_parameter = { fg = "#ac8fe4" },
			},
			context_follow_icon_color = false,
			symbols = {
				modified = "●",
				ellipsis = "…",
				separator = "❯",
			},
			kinds = icons.kinds,
		})

		vim.api.nvim_create_autocmd({
			"WinResized",
			"BufWinEnter",
			"CursorHold",
			"InsertLeave",
			"BufWritePost",
			"TextChanged",
			"TextChangedI",
		}, {
			group = vim.api.nvim_create_augroup("barbecue.updater", {}),
			callback = function()
				require("barbecue.ui").update()
			end,
		})
	end,
}
