return {}
-- return {
--         "rcarriga/nvim-notify",
--         config = function()
--                 vim.notify = require("notify")
--
--                 require("notify").setup({
--                         fps = 70,
--                         icons = {
--                                 DEBUG = " ",
--                                 ERROR = " ",
--                                 INFO = " ",
--                                 TRACE = "✎",
--                                 WARN = " ",
--                         },
--                         level = 2,
--
--                         minimum_width = 50,
--                         maximum_width = 50,
--                         render = "compact",
--                         stages = "slide",
--                         timeout = 3000,
--                 })
--         end,
-- }
