run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  # Note: max-issues-per-file: 0 means unlimited

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - typecheck
    - gosimple
    - goconst
    - gocritic
    - gofmt
    - goimports
    - lll
    - whitespace
    - cyclop
    - gocognit
    - bodyclose
    - errorlint
    - nilerr
    - rowserrcheck
    - sqlclosecheck
    - contextcheck
    - gosec

  # New structure for exclusions in v2
  exclusions:
    paths:
      - vendor/
      - testdata/
